server:
  port: '@server.port@'

management:
  security:
    flag: false
  metrics:
    export:
      statsd:
        enabled: false
        flavor: etsy
  endpoint.health.show-details: always

spring:
  application:
    name: '@project.name@'
  output:
    ansi:
      enabled: always

polling:
  enabled: false
  payouter:
    url: http://payouter:8022/repo
    delay: 10000
    retryDelay: 1000
    maxPoolSize: 1

info:
  version: '@project.version@'
  stage: dev
