server:
  port: '@server.port@'

management:
  security:
    flag: false
  metrics:
    export:
      statsd:
        enabled: false
        flavor: etsy
  endpoint.health.show-details: always

spring:
  application:
    name: '@project.name@'
  output:
    ansi:
      enabled: always
  jpa:
    database: postgresql
    properties:
      hibernate:
        default_schema: sink_drinker
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sink_drinker
    username: changeit
    password: changeit
  flyway:
    schemas: sink_drinker
    url: jdbc:postgresql://localhost:5432/sink_drinker
    user: changeit
    password: changeit

kafka:
  bootstrap-servers: localhost:9092
  topic:
    payout: payout
  ssl:
    enabled: false
    trust-store-type: PKCS12
    trust-store-location: changeit
    trust-store-password: changeit
    key-store-type: PKCS12
    key-store-location: changeit
    key-store-password: changeit
    key-password: changeit

polling:
  enabled: false
  payouter:
    sink-id: payouter
    url: http://payouter:8022/repo
    delay: 10000
    retryDelay: 1000
    maxPoolSize: 1

info:
  version: '@project.version@'
  stage: dev
