server:
  port: '@server.port@'

management:
  security:
    flag: false
  server:
    port: '@management.port@'
  metrics:
    export:
      statsd:
        flavor: etsy
        enabled: false
      prometheus:
        enabled: false
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

spring:
  application:
    name: '@project.name@'
  output:
    ansi:
      enabled: always
  jpa:
    database: postgresql
    properties:
      hibernate:
        default_schema: '@db.schema@'
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: '@db.url@'
    username: '@db.user@'
    password: '@db.password@'
    hikari:
      idle-timeout: 30000
      maximum-pool-size: 10
    flyway:
      table: schema_version
      schemas: '@db.schema@'

info:
  version: '@project.version@'
  stage: dev

kafka:
  bootstrap-servers: localhost:9092
  topic:
    payout: payout
    pm-events-payout:
      name: pm-events-payout
      produce:
        enabled: false
  ssl:
    enabled: false
    trust-store-type: PKCS12
    trust-store-location: changeit
    trust-store-password: changeit
    key-store-type: PKCS12
    key-store-location: changeit
    key-store-password: changeit
    key-password: changeit

polling:
  enabled: false
  payouter:
    url: http://payouter:8022/repo
    delay: 10000
    retryDelay: 1000
    maxPoolSize: 1

last-event:
  sink-id:
    damsel-payout: payouter
    payout-manager: payout-manager

service:
  partyManagement:
    url: http://hellgate:8022/v1/processing/partymgmt
    networkTimeout: 5000
